tasks:
  - name: Pull Images
    init: ./services create

ports:
  - name: JSON-LD context (HTTPD)
    description: Public User JSON-LD context
    port: 3004
    onOpen: notify
    visibility: public
  - name: Orion
    description: Context Broker
    port: 1026
    onOpen: notify
    visibility: public
  - name: Scorpio
    description: Context Broker
    port: 9090
    onOpen: notify
    visibility: public
  - name: Stellio
    description: Context Broker
    port: 8080
    onOpen: notify
    visibility: public
  - name: Tutorial App
    description: Web app displaying context data
    port: 3000
    onOpen: open-preview
    visibility: public
  - name: Tutorial Devices
    description: Dummy IoT Sensors over HTTP
    port: 3001
    onOpen: ignore
  - name: IoT Agent (North Port)
    description: NGSI data and device provisioning
    port: 4041
    onOpen: ignore
    visibility: public
  - name: IoT Agent (South Port)
    description: Ultralight HTTP measures
    port: 7896
    onOpen: ignore
  - name: Flink GUI
    description: Web Application
    port: 8081
    onOpen: open-preview
  - name: Flink Service
    description: Service port
    port: 9001
    onOpen: ignore
  - name: Flink Task Manager 1
    description: Task
    port: 6121
    onOpen: ignore
  - name: Flink Task Manager 2
    description: Task
    port: 6122
    onOpen: ignore
  - name: Flink Job Manager 1
    description: Job
    port: 6123
    onOpen: ignore